[2025-09-27 18:17:15,585] INFO _log() L97    * Restarting with stat - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:17:23,558] ERROR log_exception() L875  Exception on /card [POST] - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: card.clients

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\flask_openapi3\scaffold.py", line 123, in view_func
    response = func(**func_kwargs)
  File "D:\MVPs\card-offers-api\app.py", line 171, in add_card
    client.add_card(card)
    ~~~~~~~~~~~~~~~^^^^^^
  File "D:\MVPs\card-offers-api\model\client.py", line 45, in add_card
    self.cards.append(card)
    ^^^^^^^^^^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 569, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1096, in get
    value = self._fire_loader_callables(state, key, passive)
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1131, in _fire_loader_callables
    return self.callable_(state, passive)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\strategies.py", line 978, in _load_for_state
    return self._emit_lazyload(
           ~~~~~~~~~~~~~~~~~~~^
        session,
        ^^^^^^^^
    ...<7 lines>...
        execution_options,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\strategies.py", line 1141, in _emit_lazyload
    result = session.execute(
        stmt, params, execution_options=execution_options
    )
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\MVPs\card-offers-api\meu-env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: card.clients
[SQL: SELECT card.pk_card AS card_pk_card, card.name AS card_name, card."limit" AS card_limit, card."benefitCard" AS "card_benefitCard", card.inserction_date AS card_inserction_date, card.clients AS card_clients 
FROM card 
WHERE ? = card.clients]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-09-27 18:17:23,591] INFO _log() L97   127.0.0.1 - - [27/Sep/2025 18:17:23] "[35m[1mPOST /card HTTP/1.1[0m" 500 - - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:17:46,022] INFO _log() L97    * Detected change in 'D:\\MVPs\\card-offers-api\\model\\card.py', reloading - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:17:46,159] INFO _log() L97    * Restarting with stat - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:17:57,800] INFO _log() L97    * Detected change in 'D:\\MVPs\\card-offers-api\\model\\client.py', reloading - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:17:57,908] INFO _log() L97    * Restarting with stat - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:01,041] INFO _log() L97   127.0.0.1 - - [27/Sep/2025 18:18:01] "[35m[1mPOST /card HTTP/1.1[0m" 500 - - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:06,852] INFO add_client() L40   adicionando Maria - call_trace=D:\MVPs\card-offers-api\app.py L40  
[2025-09-27 18:18:06,852] INFO add_client() L45   sessão criada - call_trace=D:\MVPs\card-offers-api\app.py L45  
[2025-09-27 18:18:06,853] INFO add_client() L48   sessão add 1000.0  - call_trace=D:\MVPs\card-offers-api\app.py L48  
[2025-09-27 18:18:06,908] INFO add_client() L51   sessão commit - call_trace=D:\MVPs\card-offers-api\app.py L51  
[2025-09-27 18:18:06,910] WARNING add_client() L64   Erro ao adicionar cliente 'Marias', Não foi possível salvar novo cadastro :/ - call_trace=D:\MVPs\card-offers-api\app.py L64  
[2025-09-27 18:18:06,910] INFO _log() L97   127.0.0.1 - - [27/Sep/2025 18:18:06] "[31m[1mPOST /client HTTP/1.1[0m" 400 - - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:21,100] INFO _log() L97    * Detected change in 'D:\\MVPs\\card-offers-api\\model\\card.py', reloading - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:21,227] INFO _log() L97    * Restarting with stat - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:25,103] INFO _log() L97   127.0.0.1 - - [27/Sep/2025 18:18:25] "[35m[1mPOST /client HTTP/1.1[0m" 500 - - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:27,932] INFO _log() L97   127.0.0.1 - - [27/Sep/2025 18:18:27] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
[2025-09-27 18:18:52,109] INFO _log() L97    * Restarting with stat - call_trace=D:\MVPs\card-offers-api\meu-env\Lib\site-packages\werkzeug\_internal.py L97  
